[package]
name = "fund"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
ttl = { path = "../ttl" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
badge = { path = "../badge" }
